# Generated by Django 3.2.5 on 2023-12-04 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.TextField()),
                ('pdf', models.FileField(upload_to='pdfs/')),
                ('preview_image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('summary', models.TextField()),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='summary', to='core.article')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleMarkdown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('markdown', models.TextField()),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='markdown', to='core.article')),
            ],
        ),
    ]
