# Generated by Django 3.2.5 on 2023-12-04 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20231204_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletext',
            name='article',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parsed', to='core.article'),
        ),
    ]
