# Generated by Django 3.2.5 on 2023-12-04 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_articletext_article'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articlesummary',
            old_name='summary',
            new_name='content',
        ),
    ]
