# Generated by Django 3.2.5 on 2023-12-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_summary_articlesummary_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='preview_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
